Initial Submission of YouTube Data Ingestion and Port Integration #1
OpeyemiAdeniji/youtube-ingest pull request #1
Opened 2024-11-08 20:44 UTC by OpeyemiAdeniji

This pull request includes the initial implementation of the project for ingesting YouTube playlist and video data into Port.

2024-11-13 16:54 UTC, kodjomiles requested changes

2024-11-13 16:54 UTC, kodjomiles commented on .github/workflows/youtube-ingest.yml
> +          done
is better when you have various functionalities into jobs and you are reporting back to PORT on what's happening in the workflow as well

2024-11-13 16:54 UTC, kodjomiles commented on docs/ingest.md
> +   - Click **+ Blueprint** and select **Edit JSON**.
avoid repetition and also put the builder page link in there

2024-11-13 16:54 UTC, kodjomiles commented on docs/ingest.md
> +   - Navigate to the **Builder** page in Port.
repetition find a better way to communicate both

2024-11-13 16:54 UTC, kodjomiles commented on docs/ingest.md
> +> 💡 **TIP**
use a markdown admonition instead 
like :::tip Something about something 
      content here ---- 
      :::

2024-11-14 23:49 UTC, kodjomiles reviewed
almost there keep resolving the old comments

2024-11-15 12:12 UTC, kodjomiles reviewed
You are good to go. doing anything more will take time

2024-11-16 15:14 UTC, kodjomiles requested changes

2024-11-16 15:14 UTC, kodjomiles commented on docs/ingest.md
> +        "title": "Belongs to Playlist",
separate the content of the playlist blueprint and video blueprint. 
let's have them separately in detail collapsible

2024-11-16 15:14 UTC, kodjomiles commented on docs/ingest.md
> +  <summary>Click to copy Playlist and Video Blueprint JSON</summary>
```suggestion
  <summary><b> Playlist blueprint (click to copy)</b> </summary>
```

2024-11-16 15:14 UTC, kodjomiles commented on docs/ingest.md
> +   ```json
Have a separate detail here for Video blueprint. it makes it clearer

2024-11-16 15:14 UTC, kodjomiles commented on docs/ingest.md
> +      "belongs_to_playlist": {
change the name of the relationship . you can make it playlist. no need to add belongs to to it

2024-11-16 15:14 UTC, kodjomiles commented on docs/ingest.md
> +:::💡Tip
```suggestion
:::tip Replace placeholders
```

2024-11-16 15:18 UTC, PeyGis requested changes
nice work, man. Please go over my comments and apply the fixes

2024-11-16 15:18 UTC, PeyGis commented on docs/ingest.md
> +- **Port Actions Knowledge**: Understanding how to create and use Port actions.Learn the basics [here](https://docs.getport.io/actions-and-automations/create-self-service-experiences/setup-ui-for-act
```suggestion
- **Port Actions Knowledge**: Understanding how to create and use Port actions. Learn the basics [here](https://docs.getport.io/actions-and-automations/create-self-service-experiences/setup-ui-for-action/).
```

2024-11-16 15:18 UTC, PeyGis commented on docs/ingest.md
> +>
this sentence is good to have but delete it so we go straight to the 3 bullet point below

2024-11-16 15:18 UTC, PeyGis commented on docs/ingest.md
> +         },
delete these two properties. Every entity (an instance of a blueprint) comes with a title and identifier so you don't need to define it here again. it will be redundant

2024-11-16 15:18 UTC, PeyGis commented on docs/ingest.md
> +       "required": ["playlistId", "title"]
remove these since they are going to be removed

2024-11-16 15:18 UTC, PeyGis commented on docs/ingest.md
> +        },
delete these properties since it's redundant

2024-11-16 15:18 UTC, PeyGis commented on docs/ingest.md
> +      "required": ["videoId", "title"]
remove this as well

2024-11-16 15:18 UTC, PeyGis commented on docs/ingest.md
> +
Let's also add a hint that you have provided a static workflow file named `youtube-ingest.yml` but they can change it to any name they want as long as it is under  `.github/workflows/` folder path

2024-11-16 15:18 UTC, PeyGis commented on docs/ingest.md
> +              title: .snippet.title,
delete these since they are no longer part of the blueprint props

2024-11-16 15:18 UTC, PeyGis commented on docs/ingest.md
> +                    title: $title,
remove these two since they are no longer props of the blueprint

2024-11-16 22:32 UTC, PeyGis requested changes
more comments

2024-11-16 22:32 UTC, PeyGis commented on docs/ingest.md
> +> [!NOTE]
```suggestion
> [!Use cases]  

```

2024-11-16 22:32 UTC, PeyGis commented on docs/ingest.md
> +     "icon": "Widget",
can we use a different icon other than widget? do the same for the video blueprint icon

2024-11-16 22:32 UTC, PeyGis commented on docs/ingest.md
> +              "title": "playlistid"
rename title to Playlist ID (more user friendly)

2024-11-16 22:32 UTC, PeyGis commented on docs/ingest.md
> +
I will prefer you add a one line that says something like we will now create a github work that will serve as the backend for the port action or something.

2024-11-16 22:32 UTC, PeyGis commented on docs/ingest.md
> +3. Click **Execute** to trigger the GitHub workflow.
this section is great. maybe you can add the 4th item that says that check your Port catalog to see the video and playlist entities ingested or something equivalent

2024-11-16 22:32 UTC, PeyGis commented on docs/ingest.md
> + <summary>Setup Views widget</summary>
Setup number of views widget

2024-11-16 22:32 UTC, PeyGis commented on docs/ingest.md
> + <summary>Setup Likes widget</summary>
Setup Video likes widget

2024-11-16 22:32 UTC, PeyGis commented on docs/ingest.md
> + <summary>Setup Comments widget</summary>
Setup video/playlist comments widget

2024-11-16 22:32 UTC, PeyGis commented on docs/ingest.md
> +### Adding widgets
Add a one liner sentence that we will create 5 widgets inside the dashboard to display the metrics we're interested in

2024-11-18 16:16 UTC, PeyGis commented on docs/ingest.md
> +<summary>Video blueprint (Click to copy)</summary>
should be `click to expand`

2024-11-18 16:16 UTC, PeyGis commented on docs/ingest.md
> +  <summary>Playlist blueprint (Click to copy)</summary>
should be `click to expand`

2024-11-18 16:17 UTC, PeyGis commented on docs/ingest.md
> +<summary>Port Action (Click to copy)</summary>
should be `click to expand`

2024-11-18 16:19 UTC, PeyGis commented on docs/ingest.md
> +1. On the [self-service](https://app.getport.io/self-serve) page, select the action
be more specific such select the `Ingest Youtube Playlist` action

2024-11-18 16:20 UTC, PeyGis commented on docs/ingest.md
> +This will create a new empty dashboard. Let's get ready-to-add widgets
```suggestion
This will create a new empty dashboard. Let's get ready to add widgets.
```

2024-11-18 16:21 UTC, PeyGis commented on docs/ingest.md
> +   3. Select Aggregrate by property and choose video as the Blueprint.
```suggestion
   3. Select `Aggregrate by` property and choose video as the Blueprint.
```

2024-11-18 16:22 UTC, PeyGis commented on docs/ingest.md
> +   3. Select Aggregrate by property and choose video as the Blueprint.
please apply this formatting to all your widgets.

2024-11-18 16:24 UTC, PeyGis commented on docs/ingest.md
> +   2. Title: Views, (add the metric icon).
```suggestion
   2. Title: Enter **Views** in the input box
   3. Add an optional icon is you prefer
```

2024-11-18 16:24 UTC, PeyGis commented on docs/ingest.md
> +   2. Title: Views, (add the metric icon).
please apply this to all your widgets

2024-11-18 16:24 UTC, PeyGis commented on docs/ingest.md
> +   4. Select View Count as Property and Sum as the Function
```suggestion
   4. Select `View Count` as Property and `Sum` as the Function
```

2024-11-18 22:36 UTC, PeyGis approved these changes
well done. I think we can now submit this to Port

2024-11-18 22:36 UTC, PeyGis commented on docs/ingest.md
> +Automating the ingestion of YouTube playlist and video data into Port is not just an operational improvement but a strategic advantage. This guide aims to facilitate seamless integration, empowering
```suggestion
By following this guide, you have successfully ingested your YouTube playlist and video contents into Port.
```

2024-11-19 09:09 UTC, merged